[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "crewai>=1.7.2",
    "openai>=1.83.0",
    "pdfplumber>=0.11.8",
    "streamlit>=1.52.2",
]
